name: smart_trio_card
description: A customizable trio card carousel widget for Flutter with smooth animations, looping transitions, and interactive front card switching.
version: 1.0.0
homepage: https://github.com/fazil-kp/smart_trio_card.git
repository: https://github.com/fazil-kp/smart_trio_card.git

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
